version: "3.4"

services:
  phpappapache:
    container_name: phpappapachecontainer
    image: app-php
    build:
      context: .
      dockerfile: DockerfilePhpApache
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - .:/var/www/html/
      - ./hosts:/etc/hosts
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - phpapp-apache-network
networks:
  phpapp-apache-network:
    driver: bridge